version: "3.0"

set: ['e', 'u', 'pipefail']
shopt: ['globstar']

dotenv: ['.env']

env:
  TLD:
    sh: git rev-parse --show-toplevel
  UNAME:
    sh: "uname -s"
  VENV_DIR: ".venv"

vars:

tasks:
  default:
    desc: "Default task"
    cmds:
      - task --list

  install-devbox:
    desc: "Install devbox"
    cmds:
      - |
        if ! [[ $(command -v devbox 2>/dev/null) ]]; then
          curl -fsSL https://get.jetify.com/devbox | bash
        fi
    run: once
    silent: true

  install:
    desc: "Install project dependencies"
    env:
      VERSION: "1.5.2"
    cmds:
      - |
        asdf plugin-add terraform
        asdf install terraform {{.VERSION}}
    ignore_error: true

  gen-config:
    desc: "Generate Hugo TOML configuration"
    dir: "{{.TLD}}"
    cmds:
      - |
        jinja2 hugo.tmpl > hugo.toml

  export-reqs:
    desc: "Export requirements"
    cmds:
      - uv pip freeze | uv pip compile - -o requirements.txt

  venv:
    desc: "Create virtual environment"
    cmds:
      - uv venv {{.VENV_DIR}} --allow-existing

  pyclean:
    desc: "Remove .pyc and __pycache__"
    cmds:
      - |
        args=(
          .
          --debris
          --verbose
          -i .devbox
        )
        case "{{.CLI_ARGS}}" in
          dry-run)
            pyclean "${args[@]}" --dry-run
            ;;
          *)
            pyclean "${args[@]}"
            ;;
        esac
